name: "fin_forge"
version: "1.0.0"
profile: "fin_forge"

config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fin_forge:
    +materialized: "table"
    staging:
      +materialized: "view"
